version: "3.8"
services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - COHERE_API_KEY=kBkVGgOoZoAYkED8ySSj3CSrWfenkJVICLZj0L9Y
    volumes:
      - ./uploads:/app/uploads
      - ./static/pdfs:/app/static/pdfs
